import bcrypt from 'bcryptjs';
const data = {
    users: [
      {
        name: 'helani',    
        email: 'helanirajapakse@gmail.com',
        password: bcrypt.hashSync('1818', 8),
        isAdmin: true,
      },
      {
        name: 'NethuR',         
        email: 'nethmarajapakse@gmail.com',
        password: bcrypt.hashSync('181818', 8),
        isAdmin: false,
      },
    ],
    products: [
      {
        name: 'White long grain rice',
        category: 'Groceries',
        image: '/images/p1_White_rice.jpg',
        price: 1520, 
        countInStock: 10,
        brand: 'Palmares',
        rating: 5.0,
        numReviews: 10,
        description: 'Gold standard 5kg pack',
      },
      {
        name: 'Fresh Milk',
        category: 'Dairy',
        image: '/images/p2_Milk.jpg',
        price: 170,
        countInStock: 30,
        brand: 'None',
        rating: 4.0,
        numReviews: 3,
        description: 'Organic cows milk 1l',
      },
      {
        name: 'Black tea',
        category: 'Groceries',
        image: '/images/p3_Teavive_tea.jpg',
        price: 70,
        countInStock: 20,
        brand: 'Teavive',
        rating: 4.0,
        numReviews: 8,
        description: '100g pack',
      },
      {
        name: 'Nero black coffee',
        category: 'Groceries',
        image: '/images/p4_Nero_coffee.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nero',
        rating: 4.5,
        numReviews: 8,
        description: ' 100g pack',
      },
      {
        name: 'Hot sauce',
        category: 'Condiments',
        image: '/images/p5_Hot_sauce.jpg',
        price: 250,
        countInStock: 12,
        brand: 'Red clay original',
        rating: 4.5,
        numReviews: 13,
        description: '200ml bottle',
      },
      {
        name: 'Raw Whole Chicken',
        category: 'Meat',
        image: '/images/p6_Raw_whole_chicken.jpg',
        price: 780,
        countInStock: 12,
        brand: 'None',
        rating: 4.0,
        numReviews: 14,
        description: '1kg pack',
      },
      {
        name: 'Limes',
        category: 'Vegetables',
        image: '/images/p7_Limes.jpg',
        price: 65,
        countInStock: 5,
        brand: 'None',
        rating: 4.5,
        numReviews: 10,
        description: 'Organic - 100g pack',
      },
      {
        name: 'Red apples',
        category: 'Fruits',
        image: '/images/p8_Red_apples.jpg',
        price: 70,
        countInStock: 20,
        brand: 'None',
        rating: 4.0,
        numReviews: 8,
        description: 'Organic - 1 item',
      },
      {
        name: 'Raw prawns',
        category: 'Seafood',
        image: '/images/p9_Raw_prawns.jpg',
        price: 390,
        countInStock: 0,
        brand: 'None',
        rating: 4.8,
        numReviews: 17,
        description: '250g pack',
      },
      {
        name: 'Cherry tomatoes',
        category: 'Vegetables',
        image: '/images/p10_Red_cherry_tomatoes.jpg',
        price: 90,
        countInStock: 20,
        brand: 'None',
        rating: 4.7,
        numReviews: 11,
        description: 'Organic - 100g pack',
      },
      {
        name: 'Pure bee honey',
        category: 'Groceries',
        image: '/images/p11_Pure_bee_honey.jpg',
        price: 430,
        countInStock: 12,
        brand: 'Honey',
        rating: 4.5,
        numReviews: 15,
        description: '120g jar',
      },
      {
        name: 'Orange blossom honey',
        category: 'Groceries',
        image: '/images/p12_Sicilian_orange_blossom_honey.jpg',
        price: 550,
        countInStock: 12,
        brand: 'Sicilian',
        rating: 5.0,
        numReviews: 5,
        description: '100ml jar',
      },
      {
        name: 'Pixxden noodles',
        category: 'Groceries',
        image: '/images/p13_Pixxden_noodles.jpg',
        price: 75,
        countInStock: 12,
        brand: 'None',
        rating: 4.5,
        numReviews: 15,
        description: '100g pack',
      },
      {
        name: 'Rummo pasta',
        category: 'Groceries',
        image: '/images/p14_Rummo_pasta.jpg',
        price: 258,
        countInStock: 1,
        brand: 'Rummo',
        rating: 4.9,
        numReviews: 15,
        description: '500g pack',
      },
      {
        name: 'La creme chocolate',
        category: 'Snacks',
        image: '/images/p15_La_creme_chocolate.jpg',
        price: 180,
        countInStock: 10,
        brand: 'Cacau Show',
        rating: 4.5,
        numReviews: 25,
        description: '100g',
      },
      {
        name: 'Sprite Can',
        category: 'Beverages',
        image: '/images/p16_Sprite_can.jpg',
        price: 110,
        countInStock: 60,
        brand: 'Sprite',
        rating: 4.0,
        numReviews: 15,
        description: '250ml can',
      },
      {
        name: 'Ice cream',
        category: 'Desserts',
        image: '/images/p17_Magnum_ice_cream.jpg',
        price: 680,
        countInStock: 12,
        brand: 'Magnum',
        rating: 3.5,
        numReviews: 15,
        description: '440ml tub',
      },
      {
        name: 'Lays potato chips',
        category: 'Snacks',
        image: '/images/p18_Lays_classic_potato_chips.jpg',
        price: 150,
        countInStock: 40,
        brand: 'Lays',
        rating: 4.5,
        numReviews: 5,
        description: '50g',
      },
      {
        name: 'Orange juice',
        category: 'Beverages',
        image: '/images/p19_Minute_maid_orange_juice.jpg',
        price: 260,
        countInStock: 12,
        brand: 'Minute Maid premium',
        rating: 3.8,
        numReviews: 17,
        description: '1l',
      },
      {
        name: 'Orchard valley cashews',
        category: 'Snacks',
        image: '/images/p20_Orchard_valley_cashews.jpg',
        price: 195,
        countInStock: 27,
        brand: 'Orchard valley',
        rating: 3.8,
        numReviews: 5,
        description: '45g pack',
      },
      {
        name: 'Kaju butter cookies',
        category: 'Snacks',
        image: '/images/p21_Kaju_butter_cookies.jpg',
        price: 540,
        countInStock: 12,
        brand: 'Haldirams',
        rating: 4.5,
        numReviews: 15,
        description: '250g pack',
      },
      {
        name: 'Keratin Smooth Shampoo',
        category: 'Wellness',
        image: '/images/p22_Tresemme_shampoo.jpg',
        price: 2800,
        countInStock: 12,
        brand: 'Tresemme',
        rating: 4.5,
        numReviews: 15,
        description: '650ml bottle',
      },
      {
        name: 'Smooth & Shine conditioner',
        category: 'Wellness',
        image: '/images/p23_Tresemme_conditioner.jpg',
        price: 560,
        countInStock: 12,
        brand: 'Tresemme',
        rating: 5.0,
        numReviews: 4,
        description: '190ml bottle',
      },
      {
        name: 'Lavender soap',
        category: 'Wellness',
        image: '/images/p24_Lavender_soap.jpg',
        price: 130,
        countInStock: 20,
        brand: 'None',
        rating: 2.0,
        numReviews: 6,
        description: '180g',
      },
      {
        name: 'Tide',
        category: 'Cleaning products',
        image: '/images/p25_Tide.jpg',
        price: 400,
        countInStock: 20,
        brand: 'None',
        rating: 4.0,
        numReviews: 8,
        description: '1l',
      },
      {
        name: 'Method Dish soap',
        category: 'Cleaning products',
        image: '/images/p26_Method_dish_soap.jpg',
        price: 219,
        countInStock: 110,
        brand: 'Method',
        rating: 4.5,
        numReviews: 15,
        description: '200ml bottle',
      },
      {
        name: 'All in one lotion',
        category: 'Wellness',
        image: '/images/p27_All_in_one_lotion.jpg',
        price: 760,
        countInStock: 12,
        brand: 'Manready Mercantile',
        rating: 4.5,
        numReviews: 15,
        description: 'Bergamot and teak -200ml',
      },
      {
        name: 'Baby corn',
        category: 'Vegetables',
        image: '/images/p28_Baby_corn.jpg',
        price: 149,
        countInStock: 12,
        brand: 'Morrisons Market ST',
        rating: 4.5,
        numReviews: 15,
        description: 'Organic - 100g pack',
      },
      {
        name: 'Banana chips',
        category: 'Snacks',
        image: '/images/p29_Banana_chips.jpg',
        price: 265,
        countInStock: 12,
        brand: 'Sweet 17',
        rating: 4.2,
        numReviews: 5,
        description: '175g pack',
      },
      {
        name: 'Barbecue Sauce',
        category: 'Condiments',
        image: '/images/p30_Barbecue_sauce.jpg',
        price: 288,
        countInStock: 22,
        brand: 'Lanchero',
        rating: 3.5,
        numReviews: 60,
        description: '400g',
      },
      {
        name: 'Olive oil',
        category: 'Groceries',
        image: '/images/p31_Biologische_olive_oil.jpg',
        price: 640,
        countInStock: 12,
        brand: 'Biologische',
        rating: 4.5,
        numReviews: 15,
        description: '500ml bottle',
      },
      {
        name: 'Chakki fresh atta',
        category: 'Groceries',
        image: '/images/p32_Chakki_fresh_atta.jpg',
        price: 1900,
        countInStock: 12,
        brand: 'Rajdhani',
        rating: 4.2,
        numReviews: 15,
        description: '10kg',
      },
      {
        name: 'Bernies ketchup',
        category: 'Condiments',
        image: '/images/p33_Bernies_ketchup.jpg',
        price: 340,
        countInStock: 12,
        brand: 'Bernies burger bus',
        rating: 4.0,
        numReviews: 15,
        description: '200g',
      },
      {
        name: 'Bell Pepper',
        category: 'Vegetables',
        image: '/images/p34_Bell_pepper.jpg',
        price: 370,
        countInStock: 12,
        brand: 'None',
        rating: 4.5,
        numReviews: 15,
        description: 'Organic-3 in one pack',
      },
      {
        name: 'Clensing oil',
        category: 'Wellness',
        image: '/images/p35_Clensing_oil.jpg',
        price: 320,
        countInStock: 12,
        brand: 'Bimbimbi Botanicals',
        rating: 4.5,
        numReviews: 5,
        description: 'Nature and refresh -100ml',
      },
      {
        name: 'Fig & Rosemary candle',
        category: 'Wellness',
        image: '/images/p36_Fig_and_rosemary_soy_candle.jpg',
        price: 540,
        countInStock: 12,
        brand: 'Botanique',
        rating: 4.5,
        numReviews: 10,
        description: 'Soy candle 1 item',
      },
      {
        name: 'Coca cola can',
        category: 'Beverages',
        image: '/images/p37_Coca_cola_can.jpg',
        price: 140,
        countInStock: 50,
        brand: 'Coca cola',
        rating: 4.8,
        numReviews: 15,
        description: '355 ml',
      },
      {
        name: 'Ceylon green tea',
        category: 'Groceries',
        image: '/images/p38_Ceylon_green_tea.jpg',
        price: 500,
        countInStock: 12,
        brand: 'Emporio',
        rating: 4.9,
        numReviews: 15,
        description: 'Organic - 200g',
      },
      {
        name: 'Harpic',
        category: 'Cleaning products',
        image: '/images/p39_Harpic_blue.jpg',
        price: 240,
        countInStock: 12,
        brand: 'Harpic',
        rating: 4.5,
        numReviews: 15,
        description: '250ml',
      },
      {
        name: 'Heinz Mayonnaise',
        category: 'Condiments',
        image: '/images/p40_Heinz_mayonnaise.jpg',
        price: 310,
        countInStock: 12,
        brand: 'Heinz',
        rating: 4.5,
        numReviews: 14,
        description: '325g',
      },
      {
        name: 'Madras Lentils',
        category: 'Groceries',
        image: '/images/p41_Madras_lentils.jpg',
        price: 240,
        countInStock: 12,
        brand: 'Tasty Bite',
        rating: 4.1,
        numReviews: 10,
        description: 'Organic Indian -285g',
      },
      {
        name: 'Chili powder',
        category: 'Spices',
        image: '/images/p42_Chili_powder.jpg',
        price: 150,
        countInStock: 12,
        brand: 'Simply Organic',
        rating: 3.0,
        numReviews: 4,
        description: '82g',
      },
      {
        name: 'Peanut butter date',
        category: 'Condiments',
        image: '/images/p43_Peanut_butter_date.jpg',
        price: 390,
        countInStock: 20,
        brand: 'Date',
        rating: 4.6,
        numReviews: 4,
        description: '325g',
      },
    ],
  };
  export default data;