import bcrypt from 'bcryptjs';
const data = {
    users: [
      {
        name: 'Samadhi',    
        email: 'admin@123.com',
        password: bcrypt.hashSync('1234', 8),
        isAdmin: true,
      },
      {
        name: 'Helani',         
        email: 'user@123.com',
        password: bcrypt.hashSync('1234', 8),
        isAdmin: false,
      },
    ],
    products: [
      {
        name: 'White Rice 5kg Pack',
        category: 'Groceries',
        image: '/images/p1-white-rice.jpg',
        price: 120, 
        countInStock: 10,
        brand: 'Palmares',
        rating: 4.5,
        numReviews: 10,
        description: 'Gold',
      },
      {
        name: 'Red cherry tomatoes',
        category: 'Vegetables',
        image: '/images/p4-red-cherry-tomatoes.jpg',
        price: 100,
        countInStock: 20,
        brand: 'None',
        rating: 4.0,
        numReviews: 8,
        description: 'Organic',
      },
      {
        name: 'Raw prawns',
        category: 'Seafood',
        image: '/images/p5-raw-prawns.jpg',
        price: 220,
        countInStock: 0,
        brand: 'None',
        rating: 4.8,
        numReviews: 17,
        description: 'None',
      },
      {
        name: 'Whole Chicken',
        category: 'Meat',
        image: '/images/p6-raw-whole-chicken.jpg',
        price: 78,
        countInStock: 15,
        brand: 'None',
        rating: 4.5,
        numReviews: 14,
        description: 'None',
      },
      {
        name: 'Limes',
        category: 'Vegetables',
        image: '/images/p7-limes.jpg',
        price: 65,
        countInStock: 5,
        brand: 'None',
        rating: 4.5,
        numReviews: 10,
        description: 'Organic',
      },
      {
        name: 'Bell Pepper',
        category: 'Vegetables',
        image: '/images/p9-bell-pepper.jpg',
        price: 139,
        countInStock: 12,
        brand: 'None',
        rating: 4.5,
        numReviews: 15,
        description: 'Organic',
      },
    ],
  };
  export default data;